export const themeOne = {
   mainScreen : "bg-themeOne-background-darkBlue",
   button : "",
   toggle : "bg-themeOne-background-darkBlue :",
   containerText : "text-themeTwo-background-toggleBackground",
   inputBackground : "bg-themeOne-background-darkBlue",
   icon: "text-themeOne-background-darkRedKeyShadow",
   inputText : 'text-themeTwo-background-toggleBackground',
   buttonkeys : "bg-themeTwo-background-screenBackground",
   delButton : "bg-themeOne-background-darkBlueBackground",
   delText : "text-themeTwo-background-toggleBackground",
   resetButton : "bg-themeOne-background-darkBlueBackground",
   resetText: "text-themeTwo-background-toggleBackground",
   equalButton : "bg-themeOne-background-redBackground", 
   equalText :"text-themeTwo-background-toggleBackground",
   buttonShadow : "shadow-5xl-themeTwo-background-toggleBackground",
   equalShadow: "shadow-5xl-themeTwo-keys-darkOrangekey",
   delShadow : "shadow-5xl-themeOne-background-darkBlueBackground",
   resetShadow : "shadow-5xl-themeOne-background-darkBlueBackground",
   iconHover : "hover:text-themeTwo-keys-orangeKey",
   buttonHover : "hover:bg-text-whiteText",
   delHover : "hover:bg-themeOne-background-darkBlueKeyShadow",
   resetHover : "hover:bg-themeOne-background-darkBlueKeyShadow",
   equalHover:"hover:bg-themeOne-background-darkRedKeyShadow",
   
};